-- =====================================================================================
-- BACKUP: Source gốc sp_SalarySlip (MnuPRL445 - Phiếu lương) từ DB Vietinsoft_Pay
-- Ngày lấy: 2026-05-27
-- Mục đích: Lưu lại source hiện tại trước khi redesign ParadiseStyle
-- VI PHẠM:
--   1. Font Awesome CDN (Rule 10)
--   2. Hardcode màu Bootstrap thay vì var(--paradise-*)
--   3. <body class="bg-light"> set background (Rule 1)
--   4. <!DOCTYPE html>, <html>, <head> — không phải HTML fragment (không dùng cache)
--   5. Không có wrapper+renderer 2-layer, không MERGE tblHtmlScriptCache
--   6. Global CSS selector không scope
-- =====================================================================================
